name = "embeddy-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"
workers_dev = true

routes = [
  { pattern = "api.embeddy.link/*", zone_name = "embeddy.link" }
]

[observability]
enabled = true
